### ISSUE TITLE
Think minor import error due to case 'b' to 'B'

### ISSUE THREAD

**Issue by ruddawg26** [boolaz/BooLet#2]
Error with line 18
Traceback (most recent call last):
  File "./booLet12.py", line 18, in <module>
    from src.booLetLib import *

Need to either change the bootLet12.py code to src.BootLetLib  or change the python script in ./src/bootLetLib

Making the change fixed the problem for me.

**Comment by ruddawg26** [comment]
Additionally in line 224 of bootLet12.py another case sensitivity "L" to "l"
   fichier=script_path+"/booLet_extres/ASLlist.txt"

In the ./bootLet_extres directory the file is ASNlist.txt

**Comment by Tux-Panik** [comment]
# Tried today, I've the same issue :

$ python booLet12.py --import /path/to/files/access*
Traceback (most recent call last):
  File "./booLet12.py", line 18, in <module>
    from src.booLetLib import *

# ImportError: No module named booLetLib

**Comment by boolaz** [comment]
oops sorry, I missed your comments. I fix it asap
